#define DEFINITION_Characte

extern BOOLEAN Zgg3DDyAC_0 ARGS ((CHAR Z116[], LONGCARD , CHAR Z117[], LONGCARD ));
extern INTEGER Zgg3DDyAC_1 ARGS ((CHAR Z119[], LONGCARD ));
extern CHAR Zgg3DDyAC_2 ARGS ((CHAR Z119[], LONGCARD , INTEGER Z121));
extern void Zgg3DDyAC_3 ARGS ((CHAR Z119[], LONGCARD , CHAR Z123));
extern void Zgg3DDyAC_4 ARGS ((CHAR Z116[], LONGCARD , CHAR Z117[], LONGCARD ));
extern void Zgg3DDyAC_5 ARGS ((CHAR Z116[], LONGCARD , INTEGER Z126, INTEGER Z127, CHAR Z117[], LONGCARD ));
extern void Zgg3DDyAC_6 ARGS ((CHAR Z116[], LONGCARD , CHAR Z117[], LONGCARD ));
extern void BEGIN_Characte ARGS ((void));
